const PERMISSIONS = [
  // Core
  { key: 'core:users:view',       label: 'View Users',            module: 'core' },
  { key: 'core:users:create',     label: 'Create Users',          module: 'core' },
  { key: 'core:users:edit',       label: 'Edit Users',            module: 'core' },
  { key: 'core:users:delete',     label: 'Delete Users',          module: 'core' },
  { key: 'core:depts:view',       label: 'View Departments',      module: 'core' },
  { key: 'core:depts:create',     label: 'Create Departments',    module: 'core' },
  { key: 'core:depts:edit',       label: 'Edit Departments',      module: 'core' },
  { key: 'core:audit:view',       label: 'View Audit Logs',       module: 'core' },
  // CRM
  { key: 'crm:lead:view',         label: 'View Leads',            module: 'crm' },
  { key: 'crm:lead:create',       label: 'Create Leads',          module: 'crm' },
  { key: 'crm:lead:edit',         label: 'Edit Leads',            module: 'crm' },
  { key: 'crm:lead:delete',       label: 'Delete Leads',          module: 'crm' },
  { key: 'crm:lead:assign',        label: 'Assign Leads',          module: 'crm' },
  { key: 'crm:client:view',        label: 'View Clients',          module: 'crm' },
  { key: 'crm:client:create',      label: 'Create Clients',        module: 'crm' },
  { key: 'crm:client:edit',        label: 'Edit Clients',          module: 'crm' },
  { key: 'crm:client:delete',      label: 'Delete Clients',        module: 'crm' },
  { key: 'crm:subscription:view',  label: 'View Subscriptions',    module: 'crm' },
  { key: 'crm:subscription:edit',  label: 'Edit Subscriptions',    module: 'crm' },
  { key: 'crm:ticket:view',        label: 'View Tickets',          module: 'crm' },
  { key: 'crm:ticket:edit',        label: 'Edit Tickets',          module: 'crm' },
  // DM
  { key: 'dm:platform:view',            label: 'View DM Platforms',           module: 'dm' },
  { key: 'dm:platform:manage',          label: 'Manage DM Platforms & Tasks',  module: 'dm' },
  { key: 'dm:client_platform:view',     label: 'View Client Platform Setup',   module: 'dm' },
  { key: 'dm:client_platform:manage',   label: 'Manage Client Platform Setup', module: 'dm' },
  { key: 'dm:daily_log:view',           label: 'View DM Daily Logs',           module: 'dm' },
  { key: 'dm:daily_log:create',         label: 'Log DM Daily Tasks',           module: 'dm' },
  { key: 'dm:custom_field:manage',      label: 'Manage DM Custom Fields',      module: 'dm' },
  { key: 'dm:report:view',              label: 'View DM Reports',              module: 'dm' },
  { key: 'dm:report:generate',          label: 'Generate DM Audit Reports',    module: 'dm' },
  // GD
  { key: 'gd:task:view',     label: 'View GD Tasks',          module: 'gd' },
  { key: 'gd:task:create',   label: 'Create GD Tasks',        module: 'gd' },
  { key: 'gd:task:assign',   label: 'Assign GD Tasks',        module: 'gd' },
  { key: 'gd:task:submit',   label: 'Submit GD Work',         module: 'gd' },
  { key: 'gd:task:approve',  label: 'Approve GD Work',        module: 'gd' },
  { key: 'gd:task:deliver',  label: 'Deliver GD to Client',   module: 'gd' },
  { key: 'gd:task:revision', label: 'Request GD Revision',    module: 'gd' },
  { key: 'gd:file:upload',   label: 'Upload GD Files',        module: 'gd' },
  { key: 'gd:report:view',   label: 'View GD Reports',        module: 'gd' },
  // Dev
  { key: 'dev:project:read',      label: 'View Dev Projects',          module: 'dev' },
  { key: 'dev:project:create',    label: 'Create Dev Projects',        module: 'dev' },
  { key: 'dev:project:update',    label: 'Edit Dev Projects',          module: 'dev' },
  { key: 'dev:project:delete',    label: 'Delete Dev Projects',        module: 'dev' },
  { key: 'dev:milestone:read',    label: 'View Milestones',            module: 'dev' },
  { key: 'dev:milestone:create',  label: 'Create Milestones',          module: 'dev' },
  { key: 'dev:milestone:update',  label: 'Edit Milestones',            module: 'dev' },
  { key: 'dev:milestone:delete',  label: 'Delete Milestones',          module: 'dev' },
  { key: 'dev:task:read',         label: 'View Dev Tasks',             module: 'dev' },
  { key: 'dev:task:create',       label: 'Create Dev Tasks',           module: 'dev' },
  { key: 'dev:task:update',       label: 'Edit Dev Tasks',             module: 'dev' },
  { key: 'dev:task:delete',       label: 'Delete Dev Tasks',           module: 'dev' },
  { key: 'dev:time_log:create',   label: 'Log Dev Time',               module: 'dev' },
  { key: 'dev:bug:read',          label: 'View Bugs',                  module: 'dev' },
  { key: 'dev:bug:create',        label: 'Create Bugs',                module: 'dev' },
  { key: 'dev:bug:update',        label: 'Update Bugs',                module: 'dev' },
  { key: 'dev:bug:delete',        label: 'Delete Bugs',                module: 'dev' },
  { key: 'dev:handover:read',     label: 'View Dev Handovers',         module: 'dev' },
  { key: 'dev:handover:accept',   label: 'Accept/Clarify Dev Handovers', module: 'dev' },
  { key: 'dev:report:read',       label: 'View Dev Reports',           module: 'dev' },
  // HR — Config
  { key: 'hr:config:read',            label: 'View HR Config',            module: 'hr' },
  { key: 'hr:config:update',          label: 'Update HR Config',          module: 'hr' },
  // HR — Candidates (ATS)
  { key: 'hr:candidate:read',         label: 'View Candidates',           module: 'hr' },
  { key: 'hr:candidate:create',       label: 'Add Candidates',            module: 'hr' },
  { key: 'hr:candidate:update',       label: 'Edit Candidates',           module: 'hr' },
  { key: 'hr:candidate:delete',       label: 'Delete Candidates',         module: 'hr' },
  { key: 'hr:bulk_import:create',     label: 'Bulk Import Candidates',    module: 'hr' },
  { key: 'hr:followup:read',          label: 'View Followups',            module: 'hr' },
  { key: 'hr:followup:create',        label: 'Add Followups',             module: 'hr' },
  { key: 'hr:followup:update',        label: 'Update Followups',          module: 'hr' },
  { key: 'hr:followup:delete',        label: 'Delete Followups',          module: 'hr' },
  { key: 'hr:interview:read',         label: 'View Interviews',           module: 'hr' },
  { key: 'hr:interview:create',       label: 'Schedule Interviews',       module: 'hr' },
  { key: 'hr:interview:update',       label: 'Update Interviews',         module: 'hr' },
  { key: 'hr:interview:delete',       label: 'Delete Interviews',         module: 'hr' },
  // HR — Employees (Week 16+)
  { key: 'hr:employee:read',          label: 'View Employees',            module: 'hr' },
  { key: 'hr:employee:create',        label: 'Create Employees',          module: 'hr' },
  { key: 'hr:employee:update',        label: 'Edit Employees',            module: 'hr' },
  { key: 'hr:employee:delete',        label: 'Delete Employees',          module: 'hr' },
  { key: 'hr:employee:exit',          label: 'Process Employee Exit',     module: 'hr' },
  { key: 'hr:document:read',          label: 'View Employee Documents',   module: 'hr' },
  { key: 'hr:document:create',        label: 'Upload Employee Documents', module: 'hr' },
  { key: 'hr:self:read',              label: 'Employee Self-Service Read',module: 'hr' },
  { key: 'hr:self:update',            label: 'Employee Self-Service Edit',module: 'hr' },
  // HR — Attendance / Leave (Week 17+)
  { key: 'hr:attendance:read',        label: 'View Attendance',           module: 'hr' },
  { key: 'hr:attendance:create',      label: 'Log Attendance (Check-in)', module: 'hr' },
  { key: 'hr:attendance:update',      label: 'Manual Attendance Override',module: 'hr' },
  { key: 'hr:leave:read',             label: 'View Leave Requests',       module: 'hr' },
  { key: 'hr:leave:create',           label: 'Apply for Leave',           module: 'hr' },
  { key: 'hr:leave:approve',          label: 'Approve/Reject Leave',      module: 'hr' },
  { key: 'hr:holiday:read',           label: 'View Holidays',             module: 'hr' },
  { key: 'hr:holiday:create',         label: 'Manage Holidays',           module: 'hr' },
  // HR — Payroll (Week 18+)
  { key: 'hr:salary:read',            label: 'View Salary Data',          module: 'hr' },
  { key: 'hr:salary:update',          label: 'Update Salary Data',        module: 'hr' },
  { key: 'hr:payroll:process',        label: 'Process Payroll',           module: 'hr' },
  { key: 'hr:payroll:disburse',       label: 'Disburse Payroll',          module: 'hr' },
  { key: 'hr:self:payslip:read',      label: 'View Own Payslips',         module: 'hr' },
  { key: 'hr:reimbursement:read',     label: 'View Reimbursements',       module: 'hr' },
  { key: 'hr:reimbursement:create',   label: 'Submit Reimbursements',     module: 'hr' },
  { key: 'hr:reimbursement:approve',  label: 'Approve Reimbursements',    module: 'hr' },
  // HR — Performance (Week 19+)
  { key: 'hr:performance:read',       label: 'View Performance Data',     module: 'hr' },
  { key: 'hr:performance:create',     label: 'Create Performance Cycles', module: 'hr' },
  { key: 'hr:self:evaluation:read',   label: 'View Own Evaluations',      module: 'hr' },
  { key: 'hr:self:evaluation:create', label: 'Submit Self Evaluation',    module: 'hr' },
  { key: 'hr:peer:create',            label: 'Submit Peer Feedback',      module: 'hr' },
  // SOPs (Phase 6)
  { key: 'sops:read',             label: 'View SOPs',                 module: 'sops' },
  { key: 'sops:create',           label: 'Create/Edit SOPs',          module: 'sops' },
  { key: 'sops:delete',           label: 'Delete SOPs',               module: 'sops' },
  { key: 'sops:approve',          label: 'Approve SOPs',              module: 'sops' },
  { key: 'sops:publish',          label: 'Publish SOPs',              module: 'sops' },
  { key: 'sops:category:manage',  label: 'Manage SOP Categories',     module: 'sops' },
];

module.exports = PERMISSIONS;
