const mongoose    = require('mongoose');
const DMPlatform  = require('../models/DMPlatform');
const DMAuditMetric = require('../models/DMAuditMetric');

// Metrics per platform extracted from Ams_Final.xlsx
const METRICS_BY_CODE = {
  GMB: [
    'Page/Account Optimisation status',
    'Profile link',
    'Total reviews at start of period',
    'Total reviews at end of period',
    'New reviews received',
    'Average star rating',
    'Reviews replied',
    'Total posts published',
    'Total views (profile)',
    'Total searches',
    'Total clicks (calls, website, directions)',
    'Call clicks',
    'Website clicks',
    'Direction requests',
    'Photo views',
    'Total messages received',
    'Messages replied',
    'Major achievements',
    'Challenges faced',
    'Recommendations for next period',
    'Goals for next period',
  ],
  FACEBOOK: [
    'Page/Account Optimisation',
    'Profile link (start of project)',
    'Total followers at project start',
    'Total followers at end of period',
    'New followers gained',
    'Unfollowers count',
    'Net follower growth',
    'Total posts published',
    'Total reels/videos uploaded',
    'Total stories posted',
    'Total page reach',
    'Organic reach',
    'Paid reach (if ads were run)',
    'Total post impressions',
    'Total video views',
    'Average watch time (for videos)',
    'Total likes received',
    'Total comments received',
    'Total shares received',
    'Total saves (if applicable)',
    'Overall engagement rate',
    'Top-performing post of the period',
    'Best-performing reel/video',
    'Highest reach post',
    'Total messages received',
    'Total comments replied to',
    'Average response time',
    'Link clicks',
    'Website visits',
    'Leads generated',
    'Calls or WhatsApp inquiries',
    'Ad spend (if applicable)',
    'Cost per lead/click',
    'Return on ad spend (ROAS)',
    'Audience demographics changes',
    'Best posting day and time',
    'Key achievements this period',
    'Challenges faced',
    'Recommendations for next period',
    'Growth target for next period',
  ],
  INSTAGRAM: [
    'Page/Account Optimisation',
    'Profile link (start of project)',
    'Total followers at project start',
    'Total followers at end of period',
    'New followers gained',
    'Unfollowers count',
    'Net follower growth',
    'Total posts published',
    'Total reels/videos uploaded',
    'Total stories posted',
    'Total page reach',
    'Organic reach',
    'Paid reach (if ads were run)',
    'Total post impressions',
    'Total video views',
    'Average watch time (for videos)',
    'Total likes received',
    'Total comments received',
    'Total shares received',
    'Total saves (if applicable)',
    'Overall engagement rate',
    'Top-performing post of the period',
    'Best-performing reel/video',
    'Highest reach post',
    'Total messages received',
    'Total comments replied to',
    'Average response time',
    'Link clicks',
    'Website visits',
    'Leads generated',
    'Calls or WhatsApp inquiries',
    'Ad spend (if applicable)',
    'Cost per lead/click',
    'Return on ad spend (ROAS)',
    'Audience demographics changes',
    'Best posting day and time',
    'Key achievements this period',
    'Challenges faced',
    'Recommendations for next period',
    'Growth target for next period',
  ],
  TWITTER: [
    'Page/Account Optimisation',
    'Profile link (start of project)',
    'Total followers at project start',
    'Total followers at end of period',
    'New followers gained',
    'Unfollowers count',
    'Net follower growth',
    'Total tweets posted',
    'Total replies posted',
    'Total media posts (images/videos)',
    'Total impressions',
    'Profile visits',
    'Mentions received',
    'Link clicks',
    'Total likes',
    'Total replies',
    'Total reposts (retweets)',
    'Direct Messages (DMs) received',
    'DMs replied',
    'Mentions replied',
    'Response rate',
    'Average response time',
    'Highest impression tweet',
    'Highest engagement tweet',
    'Most reposted tweet',
    'Most clicked link tweet',
    'Total inquiries received',
    'Qualified leads',
    'Website clicks',
    'WhatsApp clicks',
    'Bio link clicks',
    'Contact button clicks (if applicable)',
    'Major achievements',
    'Challenges faced',
    'Recommendations for improvement',
    'Goals for next period',
  ],
  LINKEDIN: [
    'Page/Account Optimisation',
    'Profile link (start of project)',
    'Total followers at project start',
    'Total followers at end of period',
    'New followers/connections gained',
    'Unfollowers (for company page)',
    'Net growth',
    'Total posts published',
    'Total carousel/PDF posts uploaded',
    'Total videos uploaded',
    'Total articles published',
    'Total impressions',
    'Unique reach',
    'Profile views',
    'Company page views',
    'Search appearances',
    'Link clicks',
    'Total reactions',
    'Total comments',
    'Total shares/reposts',
    'Total saves',
    'Engagement rate',
    'Audience interaction',
    'Messages received',
    'Messages replied',
    'Comments replied',
    'Response rate',
    'Average response time',
    'Total inquiries received',
    'Qualified leads',
    'Meeting requests',
    'Calls scheduled',
    'Website clicks',
    'Contact form submissions',
    'Highest impression post',
    'Highest engagement post',
    'Most shared post',
    'Most clicked link post',
    'CTA button clicks',
    'Follower demographics changes',
    'Major achievements',
    'Challenges faced',
    'Recommendations for improvement',
    'Goals for next period',
  ],
  YOUTUBE: [
    'Channel Optimisation',
    'Profile link (start of project)',
    'Total subscribers at project start',
    'Total subscribers at end of period',
    'Total videos uploaded',
    'Total Shorts uploaded',
    'Total Community posts published',
    'Total views',
    'Total impressions',
    'Click-through rate (CTR)',
    'Unique viewers',
    'Returning viewers',
    'Total watch time (hours)',
    'Average view duration',
    'Audience retention rate',
    'Top retention video',
    'Total likes',
    'Total comments',
    'Total shares',
    'New channel memberships (if applicable)',
    'Engagement rate',
    'Comments received',
    'Comments replied',
    'Business inquiries received',
    'Sponsorship inquiries received',
    'Highest views video',
    'Highest watch time video',
    'Highest CTR video',
    'Best performing Short',
    'YouTube Search traffic %',
    'Suggested Videos traffic %',
    'Browse Features traffic %',
    'External traffic %',
    'Major achievements',
    'Challenges faced',
    'Recommendations for improvement',
    'Goals for next period',
  ],
  META_ADS: [
    'Total ad spend',
    'Daily average spend',
    'Budget utilization %',
    'Total reach',
    'Total impressions',
    'Frequency',
    'CPM (Cost per 1,000 impressions)',
    'Total link clicks',
    'Landing page views',
    'CTR (Click-Through Rate)',
    'CPC (Cost Per Click)',
    'Total leads/conversions',
    'Qualified leads',
    'Conversion rate',
    'Cost Per Lead (CPL)',
    'Feed vs Stories vs Reels performance',
    'Best-performing ad creative',
    'Highest CTR ad',
    'Lowest CPL ad',
    'Poor-performing ads paused',
    'Pixel/Conversion API status',
    'Billing/payment issues',
    'Ad rejections or policy issues',
    'Major achievements',
    'Challenges faced',
    'Optimization actions taken',
    'Recommendations for next period',
    'Growth targets for next period',
  ],
  GOOGLE_ADS: [
    'Total ad spend',
    'Daily average spend',
    'Budget utilization %',
    'Total impressions',
    'Total link clicks',
    'Total conversions/leads',
    'CPC (Cost Per Click)',
    'Cost Per Lead (CPL)',
    'Top-performing keywords',
    'Low-performing keywords',
    'Search terms reviewed',
    'Negative keywords added',
    'Average Quality Score',
    'Best-performing ads',
    'Highest CTR ads',
    'Lowest CPL ads',
    'Disapproved ads count',
    'Major achievements',
    'Challenges faced',
    'Optimization actions taken',
    'Recommendations for next period',
    'Growth targets for next period',
    'Billing/payment issues',
    'Ad rejections or policy issues',
  ],
  LINKEDIN_ADS: [
    'Total ad spend',
    'Daily average spend',
    'Budget utilization %',
    'Total impressions',
    'Total clicks',
    'CTR (Click-Through Rate)',
    'CPC (Cost Per Click)',
    'Total leads (Lead Gen Forms)',
    'Cost Per Lead (CPL)',
    'Conversion rate',
    'Top-performing campaign',
    'Best-performing ad',
    'Audience reach',
    'Billing/payment issues',
    'Ad rejections or policy issues',
    'Major achievements',
    'Challenges faced',
    'Recommendations for next period',
  ],
  ECOMMERCE: [
    'Total product listings active',
    'New products added',
    'Out-of-stock products',
    'Total orders received',
    'Total revenue',
    'Average order value',
    'Return/refund rate',
    'Total reviews received',
    'Average product rating',
    'Negative reviews addressed',
    'Ad spend (if applicable)',
    'ROAS',
    'Sponsored listing impressions',
    'Sponsored listing clicks',
    'CTR on sponsored listings',
    'Total visitors to store',
    'Conversion rate',
    'Top-selling product',
    'Major achievements',
    'Challenges faced',
    'Recommendations for next period',
  ],
  INFLUENCER: [
    'Number of influencers collaborated',
    'Total content pieces published',
    'Total reach (combined)',
    'Total impressions (combined)',
    'Total likes (combined)',
    'Total comments (combined)',
    'Total shares (combined)',
    'Total saves (combined)',
    'Overall engagement rate',
    'Story views (combined)',
    'Link clicks / Swipe-ups',
    'Leads generated',
    'WhatsApp inquiries from campaigns',
    'Cost per influencer',
    'Total campaign cost',
    'Best performing influencer',
    'Best performing content piece',
    'Major achievements',
    'Challenges faced',
    'Recommendations for next period',
  ],
  WHATSAPP_CHANNEL: [
    'Total subscribers at start',
    'Total subscribers at end',
    'New subscribers gained',
    'Total posts/broadcasts published',
    'Total reactions received',
    'Reaction rate',
    'Total link clicks',
    'Total views per post (average)',
    'Best performing post',
    'Total polls published (if any)',
    'Poll participation rate',
    'Major achievements',
    'Challenges faced',
    'Recommendations for next period',
  ],
  SMS_SHOOT: [
    'Total contacts in list',
    'Total SMSes sent',
    'Delivery rate %',
    'Failed deliveries',
    'Opt-outs received',
    'Responses received (if 2-way)',
    'Link clicks (if tracked)',
    'Leads generated',
    'Cost per SMS',
    'Total campaign cost',
    'DLT compliance status',
    'Major achievements',
    'Challenges faced',
    'Recommendations for next period',
  ],
  WAST_SHOOT: [
    'Total contacts in list',
    'Total messages sent',
    'Delivery rate %',
    'Read rate %',
    'Failed deliveries',
    'Opt-outs received',
    'Replies received',
    'Leads generated',
    'Cost per message',
    'Total campaign cost',
    'Template approval status',
    'Major achievements',
    'Challenges faced',
    'Recommendations for next period',
  ],
};

// Metrics that are numeric by nature
const NUMBER_KEYWORDS = [
  'total', 'count', 'rate', 'reach', 'impressions', 'views', 'clicks',
  'followers', 'subscribers', 'leads', 'orders', 'spend', 'cost', 'roas',
  'cpc', 'cpm', 'cpl', 'ctr', 'score', 'messages', 'replies', 'likes',
  'comments', 'shares', 'saves', 'videos', 'posts', 'growth', 'revenue',
  'average', 'frequency', 'rate', 'new', 'unfollowers', 'net', 'budget',
  'conversions', 'minutes', 'hours', 'smses', 'contacts', 'influencers',
];

const PERCENTAGE_KEYWORDS = ['rate %', 'utilization %', 'rate%', '(ctr)', '(%)'];
const CURRENCY_KEYWORDS   = ['spend', 'cost', 'revenue', 'roas', 'cpc', 'cpm', 'cpl'];

const guessValueType = (title) => {
  const t = title.toLowerCase();
  if (PERCENTAGE_KEYWORDS.some((k) => t.includes(k))) return 'percentage';
  if (CURRENCY_KEYWORDS.some((k) => t.includes(k))) return 'currency';
  if (NUMBER_KEYWORDS.some((k) => t.startsWith(k) || t.includes(' ' + k))) return 'number';
  return 'text';
};

async function seedDMAuditMetrics(systemUserId) {
  const userId = systemUserId || new mongoose.Types.ObjectId();
  let created = 0;

  for (const [code, metricList] of Object.entries(METRICS_BY_CODE)) {
    const platform = await DMPlatform.findOne({ code, deletedAt: null });
    if (!platform) continue;

    for (let i = 0; i < metricList.length; i++) {
      const title = metricList[i];
      const exists = await DMAuditMetric.findOne({ platform: platform._id, title, deletedAt: null });
      if (!exists) {
        await DMAuditMetric.create({
          platform: platform._id,
          title,
          valueType: guessValueType(title),
          sortOrder: i,
          createdBy: userId,
        });
        created++;
      }
    }
  }

  console.log(`[DM Audit Seed] Metrics: ${created} created`);
}

module.exports = { seedDMAuditMetrics };
